//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        
    	public int Id { get; set; }
        
    	private string _Name;
    	public string Name 
    	{		
    		get
    		{
    			return _Name;
    		} 
    		set
    		{
    			_Name = String.IsNullOrWhiteSpace(value) ? null : value.Trim();
    		}
     	}
    }
}
