//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Removed = false;
            this.BookCategories = new HashSet<BookCategory>();
            this.Authors = new HashSet<Author>();
        }
    
        
    	public int Id { get; set; }
        
    	private string _Title;
    	public string Title 
    	{		
    		get
    		{
    			return _Title;
    		} 
    		set
    		{
    			_Title = String.IsNullOrWhiteSpace(value) ? null : value.Trim();
    		}
     	}
        
    	private string _ISBN;
    	public string ISBN 
    	{		
    		get
    		{
    			return _ISBN;
    		} 
    		set
    		{
    			_ISBN = String.IsNullOrWhiteSpace(value) ? null : value.Trim();
    		}
     	}
        
    	public bool HardCover { get; set; }
        
    	public Nullable<System.DateTime> PublishDate { get; set; }
        
    	public short Quantity { get; set; }
        
    	private string _Location;
    	public string Location 
    	{		
    		get
    		{
    			return _Location;
    		} 
    		set
    		{
    			_Location = String.IsNullOrWhiteSpace(value) ? null : value.Trim();
    		}
     	}
        
    	public Nullable<int> PublisherId { get; set; }
        
    	private string _AdditionalInfo;
    	public string AdditionalInfo 
    	{		
    		get
    		{
    			return _AdditionalInfo;
    		} 
    		set
    		{
    			_AdditionalInfo = String.IsNullOrWhiteSpace(value) ? null : value.Trim();
    		}
     	}
        
    	public bool Removed { get; set; }
    
        public virtual ICollection<BookCategory> BookCategories { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
    }
}
