//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : Person
    {
        public Employee()
        {
            this.Removed = false;
            this.Lendings = new HashSet<Lending>();
            this.Returns = new HashSet<LentBook>();
        }
    
        
    	public byte Role { get; set; }
        
    	private string _Username;
    	public string Username 
    	{		
    		get
    		{
    			return _Username;
    		} 
    		set
    		{
    			_Username = String.IsNullOrWhiteSpace(value) ? null : value.Trim();
    		}
     	}
        
    	private string _Password;
    	public string Password 
    	{		
    		get
    		{
    			return _Password;
    		} 
    		set
    		{
    			_Password = String.IsNullOrWhiteSpace(value) ? null : value.Trim();
    		}
     	}
        
    	public bool Removed { get; set; }
    
        public virtual ICollection<Lending> Lendings { get; set; }
        public virtual ICollection<LentBook> Returns { get; set; }
    }
}
