//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LentBook
    {
        
    	public int Id { get; set; }
        
    	public Nullable<System.DateTime> ReturnDate { get; set; }
        
    	public System.DateTime EndDate { get; set; }
        
    	public int BookId { get; set; }
        
    	public int LendingId { get; set; }
        
    	public Nullable<int> ReturnEmployeeId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Employee ReturnEmployee { get; set; }
        public virtual Lending Lending { get; set; }
    }
}
