//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;

    public abstract partial class Person : IIdRecord
    {
        public Person()
        {
            this.Address = new Address();
        }
    
        
    	public int Id { get; set; }
        
    	private string _FirstName;
    	public string FirstName 
    	{		
    		get
    		{
    			return _FirstName;
    		} 
    		set
    		{
    			_FirstName = String.IsNullOrWhiteSpace(value) ? null : value.Trim();
    		}
     	}
        
    	private string _LastName;
    	public string LastName 
    	{		
    		get
    		{
    			return _LastName;
    		} 
    		set
    		{
    			_LastName = String.IsNullOrWhiteSpace(value) ? null : value.Trim();
    		}
     	}
        
    	private string _Phone;
    	public string Phone 
    	{		
    		get
    		{
    			return _Phone;
    		} 
    		set
    		{
    			_Phone = String.IsNullOrWhiteSpace(value) ? null : value.Trim();
    		}
     	}
        
    	private string _Email;
    	public string Email 
    	{		
    		get
    		{
    			return _Email;
    		} 
    		set
    		{
    			_Email = String.IsNullOrWhiteSpace(value) ? null : value.Trim();
    		}
     	}
        
    	private string _IdNumber;
    	public string IdNumber 
    	{		
    		get
    		{
    			return _IdNumber;
    		} 
    		set
    		{
    			_IdNumber = String.IsNullOrWhiteSpace(value) ? null : value.Trim();
    		}
     	}
    
        
    	public Address Address { get; set; }
    }
}
